import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import { SearchHelpPopover } from '../ui/search-help-popover';
import { RawDataPopover } from '../ui/raw-data-popover';
export function SearchResults({ results, loading, error, query, onSelect }) {
    // const metrics = useSearchMetrics();
    if (loading) {
        return (_jsx("div", { className: "mt-4 space-y-2", children: [...Array(3)].map((_, i) => (_jsx("div", { className: "h-20 rounded-lg bg-gradient-to-r from-white/5 to-white/10\n                     animate-pulse backdrop-blur-lg" }, i))) }));
    }
    if (results.length === 0 && query.length >= 2 && !error) {
        return (_jsx("div", { className: "mt-4 p-8 text-center rounded-lg\n                     bg-white/5 backdrop-blur-lg border border-white/10", children: _jsx("p", { className: "text-white/70", children: "No results found" }) }));
    }
    return (_jsx(AnimatePresence, { children: results.length > 0 && (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: 20 }, className: "relative", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("h3", { className: "text-sm font-medium text-muted-foreground", children: "Search Results" }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(RawDataPopover, { data: results }), _jsx(SearchHelpPopover, {})] })] }), _jsx("div", { className: "absolute w-full mt-2 rounded-xl overflow-hidden\n                         bg-white/10 backdrop-blur-lg border border-white/20\n                         shadow-[0_8px_32px_0_rgba(31,38,135,0.37)]", children: results.map((result, index) => (_jsxs(motion.button, { initial: { opacity: 0, x: -20 }, animate: { opacity: 1, x: 0 }, transition: { delay: index * 0.05 }, onClick: () => onSelect(result.symbol), className: "w-full p-4 text-left hover:bg-white/10\n                       border-b border-white/10 last:border-none\n                       transition-colors duration-200", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-lg font-semibold text-white", children: result.symbol }), _jsx("span", { className: "px-2 py-1 text-xs rounded-full\n                                   bg-white/20 text-white/70", children: result.type })] }), _jsx("p", { className: "text-sm text-white/70 mt-1", children: result.name })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-sm text-white/90", children: result.region }), _jsx("p", { className: "text-xs text-white/50 mt-1", children: result.currency })] })] }), _jsxs("div", { className: "mt-2 flex justify-between text-xs text-white/50", children: [_jsxs("span", { children: ["Market: ", result.marketOpen, " - ", result.marketClose, " (", result.timezone, ")"] }), _jsxs("span", { children: ["Match: ", parseInt(result.matchScore) * 100, "%"] })] })] }, result.symbol))) })] })) }));
}
