import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Calendar, DollarSign, Repeat, TrendingUp, TrendingDown } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from './ui/card';
import { Button } from './ui/button';
export function StrategyList({ strategies }) {
    return (_jsx("div", { className: "space-y-4", children: strategies.map((strategy) => (_jsxs(Card, { className: "hover:shadow-lg transition-shadow duration-200", children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs(CardTitle, { className: "text-xl flex items-center gap-2", children: [strategy.name, Math.random() > 0.5 ? (_jsx(TrendingUp, { className: "w-5 h-5 text-green-500" })) : (_jsx(TrendingDown, { className: "w-5 h-5 text-red-500" }))] }), _jsx(Button, { variant: "ghost", asChild: true, children: _jsxs(Link, { to: `/strategy/${strategy.id}`, className: "flex items-center", children: [_jsx("span", { className: "hidden sm:block mr-2", children: "View Details" }), _jsx(ArrowUpRight, { className: "w-5 h-5" })] }) })] }) }), _jsxs(CardContent, { children: [_jsxs("div", { className: "grid grid-cols-1 gap-4 sm:grid-cols-3", children: [_jsxs("div", { className: "flex items-center text-sm", children: [_jsx(DollarSign, { className: "w-4 h-4 mr-2 text-primary" }), _jsxs("div", { children: [_jsx("p", { className: "text-muted-foreground", children: "Investment" }), _jsxs("p", { className: "font-medium", children: ["$", strategy.initial_investment.toLocaleString()] })] })] }), _jsxs("div", { className: "flex items-center text-sm", children: [_jsx(Repeat, { className: "w-4 h-4 mr-2 text-primary" }), _jsxs("div", { children: [_jsx("p", { className: "text-muted-foreground", children: "Frequency" }), _jsx("p", { className: "font-medium capitalize", children: strategy.frequency })] })] }), _jsxs("div", { className: "flex items-center text-sm", children: [_jsx(Calendar, { className: "w-4 h-4 mr-2 text-primary" }), _jsxs("div", { children: [_jsx("p", { className: "text-muted-foreground", children: "Started" }), _jsx("p", { className: "font-medium", children: new Date(strategy.start_date).toLocaleDateString() })] })] })] }), _jsx("div", { className: "mt-4 h-16", children: _jsx("div", { className: "w-full h-full bg-gradient-to-r from-primary/10 via-primary/5 to-background rounded-lg" }) })] })] }, strategy.id))) }));
}
